module.exports = {
    GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
    GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
    MONGO_URI: process.env.MONGO_URI,
    COOKIE_KEY: process.env.COOKIE_KEY
};